---
- name: Set Test ID
  set_fact:
    test_id: '1.1.7'

- name: "Set other facts for {{ test_id }}"
  set_fact:
    test_mid: "1.1"
    test_name: "Corosync"
    test_desc: "Corosync expected_votes parameter is set to {{ expected[test_id] }}"
    test_remediation: "ansible"

- block:
    - import_role:
        name: post-results
        tasks_from: meta
  when:
    - always
