---

- name: Set Test ID
  set_fact:
    test_id: '1.4.2'

- name: "Set other facts for {{ test_id }}"
  set_fact:
    test_mid: "1.4"
    test_name: "Azure Fence Agent Checks"
    test_desc: "Concurrent fencing should be enabled if Azure Fence is configured {{ expected[test_id] }}"
    test_remediation: "ansible"

- name: "{{ test_id }}.result"
  shell: |
    cf_status=$(crm_attribute -t crm_config -G -n concurrent-fencing --quiet)
    if cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/@type" > /dev/null 2>&1; then
        if [[ ${cf_status} = "true" ]]; then
            echo "correct"
        else
           echo "${cf_status}"
        fi
    else
        echo "fence_azure_arm not configured"
    fi
  check_mode: no
  register: config_updated
  changed_when: config_updated.stdout != expected[test_id]
  when:
    - cloud_type == "azure"

- name: "{{ test_id }}.remediate"
  shell: 'crm configure property concurrent-fencing=true'
  register: config_updated
  when:
    - config_updated is changed
    - not ansible_check_mode
    - cloud_type == "azure"

- block:
    - import_role:
        name: post-results
  vars:
    status: "{{ config_updated is not changed }}"
  when:
    - ansible_check_mode
    - cloud_type == "azure"

