---

- name: 1.2.1
  shell: 'crm_attribute -t crm_config -G -n stonith-enabled --quiet'
  register: result
  changed_when: false

#- debug:
#    msg: "{{ result }}"

- include_role:
    name: "set-results"
  vars:
    fact_name: "1.2.1"
    fact_value: "{{ result.stdout }}"
