---

- name: 1.1.1
  shell: 'grep -E "^\s*token:" corosync.conf | sed "s/[^0-9]//g"'
  args:
    chdir: "/etc/corosync"
  register: result
  changed_when: false

- debug:
    msg: "1.1.1: Pass"
  when: result.stdout == expected['1.1.1']

- debug:
    msg: "1.1.1: Fail"
  when: result.stdout != expected['1.1.1']