---

- name: Set Test ID
  set_fact:
    test_id: '1.1.1'
    test_desc: 'stuff'
    test_remediation: 'ansible'

- name: "{{ test_id }}.remediate"
  replace:
    path: /etc/corosync/corosync.conf
    regexp: '(\s+)token:(\s)[0-9]+?$'
    replace: '\1token: {{ expected[test_id] }}'
  register: config_updated

- import_role:
    name: corosync_restart
  when:
    - config_updated is changed
    - not ansible_check_mode

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    test: "{{ test_id }}"
    desc: "{{ test_desc }}"
    status: "{{ config_updated is changed | ternary ('Failed','Passed') }}"
    remediation: "{{ test_remediation }}"
