---

- name: 1.5.4_group
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='IPaddr2']/@type" > /dev/null 2>&1; then
        is_grouped=$(cibadmin -Q --xpath "//group/primitive[@type='IPaddr2']/@type" > /dev/null 2>&1; echo $?)
        if [[ "${is_grouped}" = "0" ]]; then
            echo "is_grouped"
        else
            echo "not_grouped"
        fi
    else
        # Virtual IP is not configured
        echo "vIP RA is not configured"
    fi

  register: result_group
  changed_when: false

- debug:
    msg: "1.5.4_group: Pass"
  when: result_group.stdout == expected['1.5.4_group']

- debug:
    msg: "1.5.4_group: Fail"
  when: result_group.stdout != expected['1.5.4_group']

- name: 1.5.4_monitor_interval
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='IPaddr2']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='IPaddr2']/operations/op [@name='monitor']" | grep -oP 'interval="\K[^"]+'|| echo ""
    else
        # Virtual IP is not configured
        echo "vIP RA is not configured"
    fi

  register: result_monitor_interval
  changed_when: false

- debug:
    msg: "1.5.4_monitor_interval: Pass"
  when: result_monitor_interval.stdout == expected['1.5.4_monitor_interval']

- debug:
    msg: "1.5.4_monitor_interval: Fail"
  when: result_monitor_interval.stdout != expected['1.5.4_monitor_interval']

- name: 1.5.4_monitor_timeout
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='IPaddr2']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='IPaddr2']/operations/op [@name='monitor']" | grep -oP 'timeout="\K[^"]+' || echo ""
    else
        # Virtual IP is not configured
        echo "vIP RA is not configured"
    fi

  register: result_monitor_timeout
  changed_when: false

- debug:
    msg: "1.5.4_monitor_timeout: Pass"
  when: result_monitor_timeout.stdout == expected['1.5.4_monitor_timeout']

- debug:
    msg: "1.5.4_monitor_timeout: Fail"
  when: result_monitor_timeout.stdout != expected['1.5.4_monitor_timeout']
