---

- name: 1.4.1_pcmk_monitor_retries
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/instance_attributes/nvpair[@name='pcmk_monitor_retries']" | grep -oP 'value="\K[^"]+'|| echo ""
    else
        # Azure Fence Agent is not configured. We echo expected values just to fulfill the check
        echo 4
    fi
  register: result_pcmk_monitor_retries
  changed_when: false

- debug:
    msg: "1.4.1_pcmk_monitor_retries: Pass"
  when: result_pcmk_monitor_retries.stdout == expected['1.4.1_pcmk_monitor_retries']

- debug:
    msg: "1.4.1_pcmk_monitor_retries: Fail"
  when: result_pcmk_monitor_retries.stdout != expected['1.4.1_pcmk_monitor_retries']


- name: 1.4.1_pcmk_action_limit
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/instance_attributes/nvpair[@name='pcmk_action_limit']" | grep -oP 'value="\K[^"]+' || echo ""
    else
        # Azure Fence Agent is not configured. We echo expected values just to fulfill the check
        echo 3
    fi
  register: result_pcmk_action_limit
  changed_when: false

- debug:
    msg: "1.4.1_pcmk_action_limit: Pass"
  when: result_pcmk_action_limit.stdout == expected['1.4.1_pcmk_action_limit']

- debug:
    msg: "1.4.1_pcmk_action_limit: Fail"
  when: result_pcmk_action_limit.stdout != expected['1.4.1_pcmk_action_limit']

- name: 1.4.1_power_timeout
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/instance_attributes/nvpair[@name='power_timeout']" | grep -oP 'value="\K[^"]+' || echo ""
    else
        # Azure Fence Agent is not configured. We echo expected values just to fulfill the check
        echo 240
    fi
  register: result_power_timeout
  changed_when: false

- debug:
    msg: "1.4.1_power_timeout: Pass"
  when: result_power_timeout.stdout == expected['1.4.1_power_timeout']

- debug:
    msg: "1.4.1_power_timeout: Fail"
  when: result_power_timeout.stdout != expected['1.4.1_power_timeout']

- name: 1.4.1_pcmk_reboot_timeout
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/instance_attributes/nvpair[@name='pcmk_reboot_timeout']" | grep -oP 'value="\K[^"]+' || echo ""
    else
        # Azure Fence Agent is not configured. We echo expected values just to fulfill the check
        echo 900
    fi
  register: result_pcmk_reboot_timeout
  changed_when: false

- debug:
    msg: "1.4.1_pcmk_reboot_timeout: Pass"
  when: result_pcmk_reboot_timeout.stdout == expected['1.4.1_pcmk_reboot_timeout']

- debug:
    msg: "1.4.1_pcmk_reboot_timeout: Fail"
  when: result_pcmk_reboot_timeout.stdout != expected['1.4.1_pcmk_reboot_timeout']

- name: 1.4.1_monitor_interval
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/operations/op [@name='monitor']" | grep -oP 'interval="\K[^"]+' || echo ""
    else
        # Azure Fence Agent is not configured. We echo expected values just to fulfill the check
        echo 3600
    fi
  register: result_monitor_interval
  changed_when: false

- debug:
    msg: "1.4.1_monitor_interval: Pass"
  when: result_monitor_interval.stdout == expected['1.4.1_monitor_interval']

- debug:
    msg: "1.4.1_monitor_interval: Fail"
  when: result_monitor_interval.stdout != expected['1.4.1_monitor_interval']

- name: 1.4.1_monitor_timeout
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/operations/op [@name='monitor']" | grep -oP 'timeout="\K[^"]+' || echo ""
    else
        # Azure Fence Agent is not configured. We echo expected values just to fulfill the check
        echo 120
    fi
  register: result_monitor_timeout
  changed_when: false

- debug:
    msg: "1.4.1_monitor_timeout: Pass"
  when: result_monitor_timeout.stdout == expected['1.4.1_monitor_timeout']

- debug:
    msg: "1.4.1_monitor_timeout: Fail"
  when: result_monitor_timeout.stdout != expected['1.4.1_monitor_timeout']
