---

- name: set_results {{ test }}
  set_fact:
    ha_results: "{{ (ha_results | default({})) | combine({test: {'status': 'Fail'} }) }}"

- name: set_global_results {{ test }}
  set_fact:
    tests: "{{ (tests | default({})) | combine({test: {'result': 'Fail'} }, recursive=True) }}"

- debug:
    msg: "{{ test }} Failed"

