- hosts: all

  vars:
    ara_playbook_labels:
      - test

  tasks:
    - name: require check mode
      fail:
         msg: "Only supported for --check option"
      when:
        - not ansible_check_mode

    - name: include load_facts
      import_role:
        name: load_facts

    - name: include 1.1.1
      import_role:
        name: '1.1.1'
      when {{ name in tests_to_run }}

    - name: 1.1.1 skipped
      set_fact:
        tests: "{{ (tests | default({})) | combine({inventory_hostname: {'1.1.1': {'result': 'skipped'} } }, recursive=True) }}"
      when {{ name not in tests_to_run }}

    - name: include 1.1.1.runtime
      import_role:
        name: '1.1.1.runtime'

    - name: include 1.1.2
      import_role:
        name: '1.1.2'

    - name: include 1.1.2.runtime
      import_role:
        name: '1.1.2.runtime'

    - name: include 1.1.3
      import_role:
        name: '1.1.3'

    - name: include 1.1.3.runtime
      import_role:
        name: '1.1.3.runtime'

    - name: include 1.1.4
      import_role:
        name: '1.1.4'

    - name: include 1.1.4.runtime
      import_role:
        name: '1.1.4.runtime'

    - name: include 1.1.5
      import_role:
        name: '1.1.5'

    - name: include 1.1.5.runtime
      import_role:
        name: '1.1.5.runtime'

    - name: include 1.1.6
      import_role:
        name: '1.1.6'

    - name: include 1.1.6.runtime
      import_role:
        name: '1.1.6.runtime'

    - name: include 1.1.7
      import_role:
        name: '1.1.7'

    - name: include 1.1.8
      import_role:
        name: '1.1.8'

    - name: include 1.1.8.runtime
      import_role:
        name: '1.1.8.runtime'

    - name: include 1.2.1
      import_role:
        name: '1.2.1'

    - name: include 1.2.2
      import_role:
        name: '1.2.2'

    - name: include 1.3.1
      import_role:
        name: '1.3.1'

    - name: include 1.3.2
      import_role:
        name: '1.3.2'

    - name: include 1.3.3
      import_role:
        name: '1.3.3'

    - name: include 1.3.4
      import_role:
        name: '1.3.4'

    - name: include 1.3.5
      import_role:
        name: '1.3.5'

    - name: include 1.3.6
      import_role:
        name: '1.3.6'

    - name: include 1.3.7
      import_role:
        name: '1.3.7'

    - name: include 1.4.1.pcmk_monitor_retries_result
      import_role:
        name: '1.4.1.pcmk_monitor_retries_result'

    - name: include 1.4.1.pcmk_action_limit
      import_role:
        name: '1.4.1.pcmk_action_limit'

    - name: include 1.4.1.power_timeout
      import_role:
        name: '1.4.1.power_timeout'

    - name: include 1.4.1.pcmk_reboot_timeout
      import_role:
        name: '1.4.1.pcmk_reboot_timeout'

    - name: include 1.4.1.monitor_interval
      import_role:
        name: '1.4.1.monitor_interval'

    - name: include 1.4.1.monitor_timeout
      import_role:
        name: '1.4.1.monitor_timeout'

    - name: include 1.4.2
      import_role:
        name: '1.4.2'

    - name: include 1.5.1
      import_role:
        name: '1.5.1'

    - name: include 1.5.2
      import_role:
        name: '1.5.2'

    - name: include 1.5.3
      import_role:
        name: '1.5.3'

    - name: Set Global Results
      set_fact:
        global_results: "{{ (global_results |  default({})) | combine(hostvars[item]['tests']) }}"
      with_inventory_hostnames:
        - all
      run_once: yes
      delegate_to: localhost

    - name: Post Global Results To ARA
      ara_record:
        key: "trento-results"
        value: "{{ global_results | to_nice_json  }}"
        type: json
      run_once: yes
      delegate_to: localhost
      changed_when: false
