---

- name: 1.3.4
  shell: |
    echo -n "SBD_COUNT="
    grep -E '^SBD_DEVICE=' /etc/sysconfig/sbd |wc -l
  register: result
  changed_when: false

#- debug:
#    msg: "{{ result }}"

- include_role:
    name: "set-results"
  vars:
    fact_name: "1.3.4"
    fact_value: "{{ result.stdout }}"

