---

- name: 1.3.4.result
  shell: |
    echo -n "SBD_COUNT="
    grep -E '^SBD_DEVICE=' /etc/sysconfig/sbd |wc -l
  check_mode: no
  changed_when: false
  register: result_run

- debug: msg="1.3.4-It is recommended to configure 3 SBD devices for production environments \n References: https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker#set-up-sbd-device" 
  when:
    - result_run.stdout != expected['1.3.4']
    - not ansible_check_mode 

- block:
    - import_role:
        name: post-results
        tasks_from: fail
      when:
        - result_run.stdout != expected['1.3.4']
    - import_role:
        name: post-results
        tasks_from: pass
      when:
        - result_run.stdout != expected['1.3.4']
  when:
    - ansible_check_mode
  vars:
    test: "1.3.4"
