---
- name: 1.5.3_msl
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHana']/@type" > /dev/null 2>&1; then
        is_msl=$(cibadmin -Q --xpath "//master/primitive[@type='SAPHana']/@type" > /dev/null 2>&1; echo $?)
        if [[ "${is_msl}" = "0" ]]; then
            echo "is_msl"
        else
            echo "not_msl"
        fi
    else
        # SAPHana is not configured
        echo "SAPHana RA is not configured"
    fi

  register: result_msl
  changed_when: false

- debug:
    msg: "1.5.3_msl: Pass"
  when: result_msl.stdout == expected['1.5.3_msl']

- debug:
    msg: "1.5.3_msl: Fail"
  when: result_msl.stdout != expected['1.5.3_msl']

- name: 1.5.3_monitor_master_interval
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHana']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='SAPHana']/operations/op [@name='monitor'] [@role='Master']" | grep -oP 'interval="\K[^"]+'|| echo""
    else
        # SAPHana is not configured
        echo "SAPHana RA is not configured"
    fi

  register: result_monitor_master_interval
  changed_when: false

- debug:
    msg: "1.5.3_monitor_master_interval: Pass"
  when: result_monitor_master_interval.stdout == expected['1.5.3_monitor_master_interval']

- debug:
    msg: "1.5.3_monitor_master_interval: Fail"
  when: result_monitor_master_interval.stdout != expected['1.5.3_monitor_master_interval']

- name: 1.5.3_monitor_master_timeout
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHana']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='SAPHana']/operations/op [@name='monitor'] [@role='Master']" | grep -oP 'timeout="\K[^"]+'|| echo ""
    else
        # SAPHana is not configured
        echo "SAPHana RA is not configured"
    fi

  register: result_monitor_master_timeout
  changed_when: false

- debug:
    msg: "1.5.3_monitor_master_timeout: Pass"
  when: result_monitor_master_timeout.stdout == expected['1.5.3_monitor_master_timeout']

- debug:
    msg: "1.5.3_monitor_master_timeout: Fail"
  when: result_monitor_master_timeout.stdout != expected['1.5.3_monitor_master_timeout']

- name: 1.5.3_monitor_slave_interval
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHana']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='SAPHana']/operations/op [@name='monitor'] [@role='Slave']" | grep -oP 'interval="\K[^"]+'|| echo ""
    else
        # SAPHana is not configured
        echo "SAPHana RA is not configured"
    fi

  register: result_monitor_slave_interval
  changed_when: false

- debug:
    msg: "1.5.3_monitor_slave_interval: Pass"
  when: result_monitor_slave_interval.stdout == expected['1.5.3_monitor_slave_interval']

- debug:
    msg: "1.5.3_monitor_slave_interval: Fail"
  when: result_monitor_slave_interval.stdout != expected['1.5.3_monitor_slave_interval']

- name: 1.5.3_monitor_slave_timeout
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHana']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='SAPHana']/operations/op [@name='monitor'] [@role='Slave']" | grep -oP 'timeout="\K[^"]+'|| echo ""
    else
        # SAPHana is not configured
        echo "SAPHana RA is not configured"
    fi

  register: result_monitor_slave_timeout
  changed_when: false

- debug:
    msg: "1.5.3_monitor_slave_timeout: Pass"
  when: result_monitor_slave_timeout.stdout == expected['1.5.3_monitor_slave_timeout']

- debug:
    msg: "1.5.3_monitor_slave_timeout: Fail"
  when: result_monitor_slave_timeout.stdout != expected['1.5.3_monitor_slave_timeout']

- name: 1.5.3_start_interval
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHana']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='SAPHana']/operations/op [@name='start']" | grep -oP 'interval="\K[^"]+'|| echo ""
    else
        # SAPHana is not configured
        echo "SAPHana RA is not configured"
    fi

  register: result_start_interval
  changed_when: false

- debug:
    msg: "1.5.3_start_interval: Pass"
  when: result_start_interval.stdout == expected['1.5.3_start_interval']

- debug:
    msg: "1.5.3_start_interval: Fail"
  when: result_start_interval.stdout != expected['1.5.3_start_interval']

- name: 1.5.3_start_timeout
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHana']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='SAPHana']/operations/op [@name='start']" | grep -oP 'timeout="\K[^"]+'|| echo ""
    else
        # SAPHana is not configured
        echo "SAPHana RA is not configured"
    fi

  register: result_start_timeout
  changed_when: false

- debug:
    msg: "1.5.3_start_timeout: Pass"
  when: result_start_timeout.stdout == expected['1.5.3_start_timeout']

- debug:
    msg: "1.5.3_start_timeout: Fail"
  when: result_start_timeout.stdout != expected['1.5.3_start_timeout']

- name: 1.5.3_stop_interval
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHana']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='SAPHana']/operations/op [@name='stop']" | grep -oP 'interval="\K[^"]+'|| echo ""
    else
        # SAPHana is not configured
        echo "SAPHana RA is not configured"
    fi

  register: result_stop_interval
  changed_when: false

- debug:
    msg: "1.5.3_stop_interval: Pass"
  when: result_stop_interval.stdout == expected['1.5.3_stop_interval']

- debug:
    msg: "1.5.3_stop_interval: Fail"
  when: result_stop_interval.stdout != expected['1.5.3_stop_interval']

- name: 1.5.3_promote_interval
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHana']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='SAPHana']/operations/op [@name='promote']" | grep -oP 'interval="\K[^"]+'|| echo ""
    else
        # SAPHana is not configured
        echo "SAPHana RA is not configured"
    fi

  register: result_promote_interval
  changed_when: false

- debug:
    msg: "1.5.3_promote_interval: Pass"
  when: result_promote_interval.stdout == expected['1.5.3_promote_interval']

- debug:
    msg: "1.5.3_promote_interval: Fail"
  when: result_promote_interval.stdout != expected['1.5.3_promote_interval']

- name: 1.5.3_promote_timeout
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHana']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='SAPHana']/operations/op [@name='promote']" | grep -oP 'timeout="\K[^"]+'|| echo ""
    else
        # SAPHana is not configured
        echo "SAPHana RA is not configured"
    fi

  register: result_promote_timeout
  changed_when: false

- debug:
    msg: "1.5.3_promote_timeout: Pass"
  when: result_promote_timeout.stdout == expected['1.5.3_promote_timeout']

- debug:
    msg: "1.5.3_promote_timeout: Fail"
  when: result_promote_timeout.stdout != expected['1.5.3_promote_timeout']

- name: 1.5.3_PREFER_SITE_TAKEOVER
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHana']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='SAPHana']/instance_attributes/nvpair [@name='PREFER_SITE_TAKEOVER']" | grep -oP 'value="\K[^"]+' | tr '[:upper:]' '[:lower:]' || echo ""
    else
        # SAPHana is not configured
        echo "SAPHana RA is not configured"
    fi

  register: result_PREFER_SITE_TAKEOVER
  changed_when: false

- debug:
    msg: "1.5.3_PREFER_SITE_TAKEOVER: Pass"
  when: result_PREFER_SITE_TAKEOVER.stdout == expected['1.5.3_PREFER_SITE_TAKEOVER']

- debug:
    msg: "1.5.3_PREFER_SITE_TAKEOVER: Fail"
  when: result_PREFER_SITE_TAKEOVER.stdout != expected['1.5.3_PREFER_SITE_TAKEOVER']

- name: 1.5.3_AUTOMATED_REGISTER
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHana']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='SAPHana']/instance_attributes/nvpair [@name='AUTOMATED_REGISTER']" | grep -oP 'value="\K[^"]+' | tr '[:upper:]' '[:lower:]'|| echo ""
    else
        # SAPHana is not configured
        echo "SAPHana RA is not configured"
    fi

  register: result_AUTOMATED_REGISTER
  changed_when: false

- debug:
    msg: "1.5.3_AUTOMATED_REGISTER: Pass"
  when: result_AUTOMATED_REGISTER.stdout == expected['1.5.3_AUTOMATED_REGISTER']

- debug:
    msg: "1.5.3_AUTOMATED_REGISTER: Fail"
  when: result_AUTOMATED_REGISTER.stdout != expected['1.5.3_AUTOMATED_REGISTER']

- name: 1.5.3_DUPLICATE_PRIMARY_TIMEOUT
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHana']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='SAPHana']/instance_attributes/nvpair [@name='DUPLICATE_PRIMARY_TIMEOUT']" | grep -oP 'value="\K[^"]+'|| echo ""
    else
        # SAPHana is not configured
        echo "SAPHana RA is not configured"
    fi

  register: result_DUPLICATE_PRIMARY_TIMEOUT
  changed_when: false

- debug:
    msg: "1.5.3_DUPLICATE_PRIMARY_TIMEOUT: Pass"
  when: result_DUPLICATE_PRIMARY_TIMEOUT.stdout == expected['1.5.3_DUPLICATE_PRIMARY_TIMEOUT']

- debug:
    msg: "1.5.3_DUPLICATE_PRIMARY_TIMEOUT: Fail"
  when: result_DUPLICATE_PRIMARY_TIMEOUT.stdout != expected['1.5.3_DUPLICATE_PRIMARY_TIMEOUT']
