---

- name: Set Test ID
  set_fact:
    test_id: '1.3.1'

- name: "Set other facts for {{ test_id }}"
  set_fact:
    test_mid: "1.3"
    test_name: "SBD"
    test_desc: "Pacemaker and SBD integration is enabled {{ expected[test_id] }}"
    test_remediation: "ansible"

- block:
    - import_role:
        name: post-results
        tasks_from: meta
  when:
    - always
