---

- name: 1.3.1.result
  shell: 'grep SBD_PACEMAKER sbd'
  args:
    chdir: "/etc/sysconfig/"
  check_mode: no
  register: result
  changed_when: false

- import_role:
    name: cluster_stop
  when:
    - result.stdout != expected['1.3.1'] 
    - not ansible_check_mode
    - inventory_hostname == groups.target[0]

- name: 1.3.1.remediate
  replace:
    path: /etc/sysconfig/sbd
    regexp: '^\s*SBD_PACEMAKER=[a-zA-Z]+?$'
    replace: '{{ expected["1.3.1"] }}'
  register: config_updated

- import_role:
    name: cluster_start
  when:
    - config_updated is changed
    - not ansible_check_mode
    - inventory_hostname == groups.target[0]

