---

- name: 1.3.2
  shell: 'grep SBD_STARTMODE sbd'
  args:
    chdir: "/etc/sysconfig/"
  register: result
  changed_when: false

#- debug:
#    msg: "{{ result }}"

- include_role:
    name: "set-results"
  vars:
    fact_name: "1.3.2"
    fact_value: "{{ result.stdout }}"

