---

- name: Set Test ID
  set_fact:
    test_id: '1.3.2'

- name: "Set other facts for {{ test_id }}"
  set_fact:
    test_mid: "1.3"
    test_name: "SBD"
    test_desc: "SBD start mode is set to always {{ expected[test_id] }}"
    test_remediation: "ansible"

- name: "{{ test_id }}.result"
  shell: 'grep SBD_STARTMODE sbd'
  args:
    chdir: "/etc/sysconfig/"
  check_mode: no
  register: result
  changed_when: false

- import_role:
    name: cluster_stop
  when:
    - not ansible_check_mode
    - inventory_hostname == groups.target[0]
    - result.stdout != expected[test_id]

- name: "{{ test_id }}.remediate"
  replace:
    path: /etc/sysconfig/sbd
    regexp: '^\s*SBD_STARTMODE=[a-zA-Z]+?$'
    replace: '{{ expected[test_id] }}'
  register: config_updated

- import_role:
    name: cluster_start
  when:
    - config_updated is changed
    - not ansible_check_mode
    - inventory_hostname == groups.target[0]

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is changed | ternary ('Failed','Passed') }}"
