---

- name: Set Test ID
  set_fact:
    test_id: '1.3.2'

- name: "Set other facts for {{ test_id }}"
  set_fact:
    test_mid: "1.3"
    test_name: "SBD"
    test_desc: "SBD start mode is set to always {{ expected[test_id] }}"
    test_remediation: "ansible"

