---

- name: Set Test ID
  set_fact:
    test_id: '2.1.6'
  delegate_to: localhost

- name: "{{ test_id }}.check"
  shell: |
    #   if rsc_colocation constraint is not configured, then fail
    cibadmin -Q --xpath "//constraints/rsc_colocation" || exit 1
    #   if rsc_order constraint is not configured, then fail
    cibadmin -Q --xpath "//constraints/rsc_order" || exit 1

    # Check that following match expected, exit with error if any do not
    XPATH="//constraints/rsc_colocation [contains(@id, 'col_saphana')]"
    [[ $(cibadmin -Q --xpath "${XPATH}" | grep -oP ' score="\K[^"]+') != "{{ expected[test_id + '.rsc_colocation_score'] }}" ]] && exit 1
    [[ $(cibadmin -Q --xpath "${XPATH}" | grep -oP ' rsc="\K[^"]+' | grep -o g_ip) != "{{ expected[test_id + '.rsc_colocation_rsc'] }}" ]] && exit 1
    [[ $(cibadmin -Q --xpath "${XPATH}" | grep -oP ' rsc-role="\K[^"]+') != "{{ expected[test_id + '.rsc_colocation_rsc_role'] }}" ]] && exit 1
    [[ $(cibadmin -Q --xpath "${XPATH}" | grep -oP ' with-rsc="\K[^"]+' | grep -o msl_SAPHana) != "{{ expected[test_id + '.rsc_colocation_with_rsc'] }}" ]] && exit 1
    [[ $(cibadmin -Q --xpath "${XPATH}" | grep -oP ' with-rsc-role="\K[^"]+') != "{{ expected[test_id + '.rsc_colocation_with_rsc_role'] }}" ]] && exit 1

    XPATH="//constraints/rsc_order [contains(@id, 'ord_SAPHana')]"
    [[ $(cibadmin -Q --xpath "${XPATH}" | grep -oP ' kind="\K[^"]+') != "{{ expected[test_id + '.rsc_order_kind'] }}" ]] && exit 1
    [[ $(cibadmin -Q --xpath "${XPATH}" | grep -oP ' first="\K[^"]+' | grep -o cln_SAPHanaTopology) != "{{ expected[test_id + '.rsc_order_first'] }}" ]] && exit 1
    [[ $(cibadmin -Q --xpath "${XPATH}" | grep -oP ' then="\K[^"]+' | grep -o msl_SAPHana) != "{{ expected[test_id + '.rsc_order_then'] }}" ]] && exit 1
    exit 0
  check_mode: no
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
