---

- name: Set Test ID
  set_fact:
    test_id: '2.1.5'
  delegate_to: localhost

- name: "{{ test_id }}.check"
  shell: |
    #  if azure-lb RA is not configured, then fail
    cibadmin -Q --xpath "//primitive[@type='azure-lb']/@type" || exit 1
    # if not grouped, exit with fail
    cibadmin -Q --xpath "//group/primitive[@type='azure-lb']/@type" || exit 1
    # Check that following match expected, exit with error if any do not
    [[ $(cibadmin -Q --xpath "//primitive[@type='azure-lb']/meta_attributes/nvpair [@name='resource-stickiness']" | grep -oP 'value="\K[^"]+') != "{{ expected[test_id + '.nvpair_resource_stickiness'] }}" ]] && exit 1
    exit 0 
  check_mode: no
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
