---
cloud_type: "azure"

expected:
  "1.1.1": "30000"
  "1.1.1_runtime": "30000"
  "1.1.2": "36000"
  "1.1.2_runtime": "36000"
  "1.1.3": "20"
  "1.1.3_runtime": "20"
  "1.1.4": "60"
  "1.1.4_runtime": "60"
  "1.1.5": "10"
  "1.1.5_runtime": "10"
  "1.1.6": "udpu"
  "1.1.7": "2"
  "1.1.8": "1"
  "1.1.8_runtime": "1"
  "1.2.1": "true"
  "1.2.2": "correct"
  "1.3.1": "SBD_PACEMAKER=yes"
  "1.3.2": "SBD_STARTMODE=always"
  "1.3.3": "enabled"
  "1.3.4": "SBD_COUNT=3"
  "1.3.5": "60"
  "1.3.6": "120"
  "1.4.1.monitor_interval": "3600"
  "1.4.1.monitor_timeout": "120"
  "1.4.1.pcmk_action_limit": "3"
  "1.4.1.pcmk_monitor_retries": "4"
  "1.4.1.pcmk_reboot_timeout": "900"
  "1.4.1.power_timeout": "240"
  "1.4.2": "correct OR fence_azure_arm not configured"
  "1.5.1": "pass"
  "1.5.2": "blocked"
  "1.5.3": "passed"
