---

- name: Set Test ID
  set_fact:
    test_id: '1.1.6'
    key_name: 'transport'
  delegate_to: localhost

- name: "{{ test_id }}.check"
  lineinfile:
    path: /etc/corosync/corosync.conf
    regexp: '^(\s+){{ key_name }}:'
    line: "\t{{ key_name }}: {{ expected[test_id] }}"
    insertafter: 'totem {'
  register: config_updated
  when: ansible_check_mode

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
