---

- name: 1.6.1_sidadm
  shell: |
    cat /etc/sudoers | grep -E ".+ +ALL=\(ALL\) +NOPASSWD: +/usr/sbin/crm_attribute +-n +hana_.+_site_srHook_\*" | sed "s/.*/true/"
  register: result_sidadm
  changed_when: false

- debug:
    msg: "1.6.1_sidadm: Pass"
  when: result_sidadm.stdout == expected['1.6.1_sidadm']

- debug:
    msg: "1.6.1_sidadm: Fail"
  when: result_sidadm.stdout != expected['1.6.1_sidadm']

- name: 1.6.1_SOK_SITEA
  shell: |
    cat /etc/sudoers | grep -E "^Cmnd_Alias +SOK_SITEA += +/usr/sbin/crm_attribute" | grep -E "\-n +hana_.+_site_srHook_.+" | grep -E "\-v +SOK" | grep -E "\-t +crm_config" | grep -E "\-s +SAPHanaSR" | sed "s/.*/true/"
  register: result_SOK_SITEA
  changed_when: false

- debug:
    msg: "1.6.1_SOK_SITEA: Pass"
  when: result_SOK_SITEA.stdout == expected['1.6.1_SOK_SITEA']

- debug:
    msg: "1.6.1_SOK_SITEA: Fail"
  when: result_SOK_SITEA.stdout != expected['1.6.1_SOK_SITEA']

- name: 1.6.1_SFAIL_SITEA
  shell: |
    cat /etc/sudoers | grep -E "^Cmnd_Alias +SFAIL_SITEA += +/usr/sbin/crm_attribute" | grep -E "\-n +hana_.+_site_srHook_.+" | grep -E "\-v +SFAIL" | grep -E "\-t +crm_config" | grep -E "\-s +SAPHanaSR" | sed "s/.*/true/"
  register: result_SFAIL_SITEA
  changed_when: false

- debug:
    msg: "1.6.1_SFAIL_SITEA: Pass"
  when: result_SFAIL_SITEA.stdout == expected['1.6.1_SFAIL_SITEA']

- debug:
    msg: "1.6.1_SFAIL_SITEA: Fail"
  when: result_SFAIL_SITEA.stdout != expected['1.6.1_SFAIL_SITEA']

- name: 1.6.1_SOK_SITEB
  shell: |
    cat /etc/sudoers | grep -E "^Cmnd_Alias +SOK_SITEB += +/usr/sbin/crm_attribute" | grep -E "\-n +hana_.+_site_srHook_.+" | grep -E "\-v +SOK" | grep -E "\-t +crm_config" | grep -E "\-s +SAPHanaSR" | sed "s/.*/true/"
  register: result_SOK_SITEB
  changed_when: false

- debug:
    msg: "1.6.1_SOK_SITEB: Pass"
  when: result_SOK_SITEB.stdout == expected['1.6.1_SOK_SITEB']

- debug:
    msg: "1.6.1_SOK_SITEB: Fail"
  when: result_SOK_SITEB.stdout != expected['1.6.1_SOK_SITEB']

- name: 1.6.1_SFAIL_SITEB
  shell: |
    cat /etc/sudoers | grep -E "^Cmnd_Alias +SFAIL_SITEB += +/usr/sbin/crm_attribute" | grep -E "\-n +hana_.+_site_srHook_.+" | grep -E "\-v +SFAIL" | grep -E "\-t +crm_config" | grep -E "\-s +SAPHanaSR" | sed "s/.*/true/"
  register: result_SFAIL_SITEB
  changed_when: false

- debug:
    msg: "1.6.1_SFAIL_SITEB: Pass"
  when: result_SFAIL_SITEB.stdout == expected['1.6.1_SFAIL_SITEB']

- debug:
    msg: "1.6.1_SFAIL_SITEB: Fail"
  when: result_SFAIL_SITEB.stdout != expected['1.6.1_SFAIL_SITEB']

- name: 1.6.1_sidadm_all
  shell: |
    cat /etc/sudoers | grep -E ".+ +ALL=\(ALL\) +NOPASSWD:" | sed "s/.*: //" | grep SOK_SITEA | grep SFAIL_SITEA | grep SOK_SITEB | grep SFAIL_SITEB | sed "s/.*/true/"
  register: result_sidadm_all
  changed_when: false

- debug:
    msg: "1.6.1_sidadm_all: Pass"
  when: result_sidadm_all.stdout == expected['1.6.1_sidadm_all']

- debug:
    msg: "1.6.1_sidadm_all: Fail"
  when: result_sidadm_all.stdout != expected['1.6.1_sidadm_all']
