---

- name: 1.5.1_resource
  shell: |
    crm_attribute -t rsc_defaults -G -n resource-stickiness --quiet
  register: result_resource
  changed_when: false

#- debug:
#    msg: "{{ result_resource }}"

- include_role:
    name: "set-results"
  vars:
    fact_name: "1.5.1_resource"
    fact_value: "{{ result_resource.stdout }}"

- name: 1.5.1_migration
  shell: |
    crm_attribute -t rsc_defaults -G -n migration-threshold --quiet
  register: result_migration
  changed_when: false

#- debug:
#    msg: "{{ result_migration }}"

- include_role:
    name: "set-results"
  vars:
    fact_name: "1.5.1_migration"
    fact_value: "{{ result_migration.stdout }}"
