---

- name: 1.3.3
  shell: 'systemctl is-enabled sbd'
  register: result
  changed_when: false

- debug:
    msg: "1.3.3: Pass"
  when: result.stdout == expected['1.3.3']

- debug:
    msg: "1.3.3: Fail"
  when: result.stdout != expected['1.3.3']
