---

- name: Set Test ID
  set_fact:
    test_id: '1.3.3'

- name: "Set other facts for {{ test_id }}"
  set_fact:
    test_mid: "1.3"
    test_name: "SBD"
    test_desc: "SBD service is enabled {{ expected[test_id] }}"
    test_remediation: "ansible"

- name: "{{ test_id }}.result"
  shell: 'systemctl is-enabled sbd || true'
  check_mode: no
  register: config_updated
  changed_when: config_updated.stdout != expected[test_id]

- name: "{{ test_id }}.remediate"
  shell: 'systemctl enable sbd'
  register: config_updated
  when:
    - config_updated is changed
    - not ansible_check_mode

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is changed | ternary ('Failed','Passed') }}"
