---

- name: 1.3.3
  shell: 'systemctl is-enabled sbd'
  register: result
  changed_when: false

#- debug:
#    msg: "{{ result }}"

- include_role:
    name: "set-results"
  vars:
    fact_name: "1.3.3"
    fact_value: "{{ result.stdout }}"

