---

- name: Set Test ID
  set_fact:
    test_id: '2.2.1'
  delegate_to: localhost

- name: "{{ test_id }}.check"
  shell: |
    # 
    readlink /etc/products.d/baseproduct | grep -i "{{ expected [test_id] }}" || exit 1
    exit 0
  check_mode: no
  register: config_updated
  changed_when: config_updated.rc != 0
  failed_when: config_updated.rc > 1

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
