---

- name: Set Test ID
  set_fact:
    test_id: '1.1.5.runtime'

- name: "Set other facts for {{ test_id }}"
  set_fact:
    test_mid: "1.1"
    test_name: "Corosync"
    test_desc: " Corosync token_retransmits_before_loss_const parameter is set to {{ expected[test_id] }} runtime"
    test_remediation: "ansible"

- name: "{{ test_id }}.remediate"
  shell: 'corosync-cmapctl | grep "runtime.config.totem.token_retransmits_before_loss_const (u32) = " | sed "s/^.*= //"'
  check_mode: no
  register: result_run
  changed_when: false

- import_role:
    name: 'corosync_restart'
    tasks_from: main
  when:
    - result_run.stdout != expected['1.1.5']
    - not ansible_check_mode
