---

- name: 1.5.5_group
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='azure-lb']/@type" > /dev/null 2>&1; then
        is_grouped=$(cibadmin -Q --xpath "//group/primitive[@type='azure-lb']/@type" > /dev/null 2>&1; echo $?)
        if [[ "${is_grouped}" = "0" ]]; then
            echo "is_grouped"
        else
            echo "not_grouped"
        fi
    else
        # azure-lb RA is not configured
        echo "azure-lb RA is not configured"
    fi

  register: result_group
  changed_when: false

#- debug:
#    msg: "{{ result_group }}"

- include_role:
    name: "set-results"
  vars:
    fact_name: "1.5.5_group"
    fact_value: "{{ result_group.stdout }}"

- name: 1.5.5_resource_stickiness
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='azure-lb']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='azure-lb']/meta_attributes/nvpair [@name='resource-stickiness']" | grep -oP 'value="\K[^"]+'
    else
        # azure-lb RA is not configured
        echo "azure-lb RA is not configured"
    fi

  register: result_resource_stickiness
  changed_when: false

#- debug:
#    msg: "{{ result_resource_stickiness }}"

- include_role:
    name: "set-results"
  vars:
    fact_name: "1.5.5_resource_stickiness"
    fact_value: "{{ result_resource_stickiness.stdout }}"

