---

- name: 1.5.6_rsc_colocation_score
  shell: |
    if cibadmin -Q --xpath "//constraints/rsc_colocation" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//constraints/rsc_colocation" | grep -oP ' score="\K[^"]+'|| echo ""
    else
        # Colocation constraint is not configured
        echo "colocation constraint is not configured"
    fi

  register: result_rsc_colocation_score
  changed_when: false

- debug:
    msg: "1.5.6_rsc_colocation_score: Pass"
  when: result_rsc_colocation_score.stdout == expected['1.5.6_rsc_colocation_score']

- debug:
    msg: "1.5.6_rsc_colocation_score: Fail"
  when: result_rsc_colocation_score.stdout != expected['1.5.6_rsc_colocation_score']

- name: 1.5.6_rsc_colocation_rsc
  shell: |
    if cibadmin -Q --xpath "//constraints/rsc_colocation" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//constraints/rsc_colocation" | grep -oP ' rsc="\K[^"]+' | grep -o g_ip || echo ""
    else
        # Colocation constraint is not configured
        echo "colocation constraint is not configured"
    fi

  register: result_rsc_colocation_rsc
  changed_when: false

- debug:
    msg: "1.5.6_rsc_colocation_rsc: Pass"
  when: result_rsc_colocation_rsc.stdout == expected['1.5.6_rsc_colocation_rsc']

- debug:
    msg: "1.5.6_rsc_colocation_rsc: Fail"
  when: result_rsc_colocation_rsc.stdout != expected['1.5.6_rsc_colocation_rsc']

- name: 1.5.6_rsc_colocation_rsc_role
  shell: |
    if cibadmin -Q --xpath "//constraints/rsc_colocation" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//constraints/rsc_colocation" | grep -oP ' rsc-role="\K[^"]+' || echo ""
    else
        # Colocation constraint is not configured
        echo "colocation constraint is not configured"
    fi

  register: result_rsc_colocation_rsc_role
  changed_when: false

- debug:
    msg: "1.5.6_rsc_colocation_rsc_role: Pass"
  when: result_rsc_colocation_rsc_role.stdout == expected['1.5.6_rsc_colocation_rsc_role']

- debug:
    msg: "1.5.6_rsc_colocation_rsc_role: Fail"
  when: result_rsc_colocation_rsc_role.stdout != expected['1.5.6_rsc_colocation_rsc_role']

- name: 1.5.6_rsc_colocation_with_rsc
  shell: |
    if cibadmin -Q --xpath "//constraints/rsc_colocation" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//constraints/rsc_colocation" | grep -oP ' with-rsc="\K[^"]+' | grep -o msl_SAPHana || echo ""
    else
        # Colocation constraint is not configured
        echo "colocation constraint is not configured"
    fi

  register: result_rsc_colocation_with_rsc
  changed_when: false

- debug:
    msg: "1.5.6_rsc_colocation_with_rsc: Pass"
  when: result_rsc_colocation_with_rsc.stdout == expected['1.5.6_rsc_colocation_with_rsc']

- debug:
    msg: "1.5.6_rsc_colocation_with_rsc: Fail"
  when: result_rsc_colocation_with_rsc.stdout != expected['1.5.6_rsc_colocation_with_rsc']

- name: 1.5.6_rsc_colocation_with_rsc_role
  shell: |
    if cibadmin -Q --xpath "//constraints/rsc_colocation" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//constraints/rsc_colocation" | grep -oP ' with-rsc-role="\K[^"]+' || echo ""
    else
        # Colocation constraint is not configured
        echo "colocation constraint is not configured"
    fi

  register: result_rsc_colocation_with_rsc_role
  changed_when: false

- debug:
    msg: "1.5.6_rsc_colocation_with_rsc_role: Pass"
  when: result_rsc_colocation_with_rsc.stdout == expected['1.5.6_rsc_colocation_with_rsc_role']

- debug:
    msg: "1.5.6_rsc_colocation_with_rsc_role: Fail"
  when: result_rsc_colocation_with_rsc.stdout != expected['1.5.6_rsc_colocation_with_rsc_role']

- name: 1.5.6_rsc_order_kind
  shell: |
    if cibadmin -Q --xpath "//constraints/rsc_order" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//constraints/rsc_order" | grep -oP ' kind="\K[^"]+' || echo ""
    else
        # Colocation constraint is not configured
        echo "order constraint is not configured"
    fi

  register: result_rsc_order_kind
  changed_when: false

- debug:
    msg: "1.5.6_rsc_order_kind: Pass"
  when: result_rsc_order_kind.stdout == expected['1.5.6_rsc_order_kind']

- debug:
    msg: "1.5.6_rsc_order_kind: Fail"
  when: result_rsc_order_kind.stdout != expected['1.5.6_rsc_order_kind']

- name: 1.5.6_rsc_order_first
  shell: |
    if cibadmin -Q --xpath "//constraints/rsc_order" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//constraints/rsc_order" | grep -oP ' first="\K[^"]+' | grep -o cln_SAPHanaTopology || echo ""
    else
        # Colocation constraint is not configured
        echo "order constraint is not configured"
    fi

  register: result_rsc_order_first
  changed_when: false

- debug:
    msg: "1.5.6_rsc_order_first: Pass"
  when: result_rsc_order_first.stdout == expected['1.5.6_rsc_order_first']

- debug:
    msg: "1.5.6_rsc_order_first: Fail"
  when: result_rsc_order_first.stdout != expected['1.5.6_rsc_order_first']

- name: 1.5.6_rsc_order_then
  shell: |
    if cibadmin -Q --xpath "//constraints/rsc_order" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//constraints/rsc_order" | grep -oP ' then="\K[^"]+' | grep -o msl_SAPHana || echo ""
    else
        # Colocation constraint is not configured
        echo "order constraint is not configured"
    fi

  register: result_rsc_order_then
  changed_when: false

- debug:
    msg: "1.5.6_rsc_order_then: Pass"
  when: result_rsc_order_then.stdout == expected['1.5.6_rsc_order_then']

- debug:
    msg: "1.5.6_rsc_order_then: Fail"
  when: result_rsc_order_then.stdout != expected['1.5.6_rsc_order_then']
