---

- name: Set Test ID
  set_fact:
    test_id: '1.4.1.monitor_interval'

- name: "Set other facts for {{ test_id }}"
  set_fact:
    test_mid: "1.4"
    test_name: "Azure Fence Agent Checks"
    test_desc: "Azure Fence Agent retries and timeout parameters check monitor interval={{ expected[test_id] }}"
    test_remediation: |
          ## Abstract
          The Azure SAP Clustering best practices determines specific timing and retries parameter values for proper
          functioning of the Azure Fence agent.

          ## Remediation
          Please, make sure to set the following values for the fence-agent parameter : monitor interval=3600
          ## References
          <pre>-  https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker#1-create-the-stonith-devices</pre>

- name: "{{ test_id }}"
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='fence_azure_arm']/operations/op [@name='monitor']" | grep -oP 'interval="\K[^"]+' || echo ""
    else
        # Azure Fence Agent is not configured. We echo expected values just to fulfill the check
        echo 3600
    fi
  check_mode: no
  register: config_updated
  changed_when: config_updated.stdout != expected[test_id]
  when:
    - cloud_type == "azure"

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is changed | ternary ('Failed','Passed') }}"
