---

- name: 1.1.2.runtime
  shell:  'corosync-cmapctl | grep "runtime.config.totem.consensus (u32) = " | sed "s/^.*= //"'
  register: result
  changed_when: false

- include_role:
    name: "set-results"
  vars:
    fact_name: "1.1.2.runtime"
    fact_value: "{{ result.stdout }}"
