---

- name: Set Test ID
  set_fact:
    test_id: '2.2.8'
  delegate_to: localhost

- name: "{{ test_id }}.check"
  shell: |
    #  HANA and SPS versions are compatible
    sid=$(sudo crm configure show | grep -m1 SID= | sed -e "s/.*SID=\(...\).*/\1/" | tr '[:upper:]' '[:lower:]')
    full_version=$(sudo -i -u ${sid}adm HDB version | grep "version:" | sed -e "s/^.*:[\ ]*//")
    if [[ "$full_version" = "" ]]; then
      echo "0"
    else
      echo "$full_version"
    fi
  check_mode: no
  register: config_updated
  changed_when: config_updated.stdout is version(expected[test_id], '<')
  failed_when: config_updated.rc > 0

- block:
    - import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
