---

- name: 1.5.2_clone
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHanaTopology']/@type" > /dev/null 2>&1; then
        is_clone=$(cibadmin -Q --xpath "//clone/primitive[@type='SAPHanaTopology']/@type" > /dev/null 2>&1; echo $?)
        if [[ "${is_clone}" = "0" ]]; then
            echo "is_clone"
        else
            echo "not_clone"
        fi
    else
        # SAPHanaTopology is not configured
        echo "SAPHanaTopology is not configured"
    fi
  register: result_clone
  changed_when: false

#- debug:
#    msg: "{{ result_clone }}"

- include_role:
    name: "set-results"
  vars:
    fact_name: "1.5.2_clone"
    fact_value: "{{ result_clone.stdout }}"

- name: 1.5.2_monitor_interval
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHanaTopology']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='SAPHanaTopology']/operations/op [@name='monitor']" | grep -oP 'interval="\K[^"]+'||echo ""
    else
        # SAPHanaTopology is not configured
        echo "SAPHanaTopology is not configured"
    fi
  register: result_monitor_interval
  changed_when: false

#- debug:
#    msg: "{{ result_monitor_interval }}"

- include_role:
    name: "set-results"
  vars:
    fact_name: "1.5.2_monitor_interval"
    fact_value: "{{ result_monitor_interval.stdout }}"

- name: 1.5.2_monitor_timeout
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHanaTopology']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='SAPHanaTopology']/operations/op [@name='monitor']" | grep -oP 'timeout="\K[^"]+'||echo ""
    else
        # SAPHanaTopology is not configured
        echo "SAPHanaTopology is not configured"
    fi
  register: result_monitor_timeout
  changed_when: false

#- debug:
#    msg: "{{ result_monitor_timeout }}"

- include_role:
    name: "set-results"
  vars:
    fact_name: "1.5.2_monitor_timeout"
    fact_value: "{{ result_monitor_timeout.stdout }}"

- name: 1.5.2_start_interval
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHanaTopology']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='SAPHanaTopology']/operations/op [@name='start']" | grep -oP 'interval="\K[^"]+'||echo ""
    else
        # SAPHanaTopology is not configured
        echo "SAPHanaTopology is not configured"
    fi
  register: result_start_interval
  changed_when: false

#- debug:
#    msg: "{{ result_start_interval }}"

- include_role:
    name: "set-results"
  vars:
    fact_name: "1.5.2_start_interval"
    fact_value: "{{ result_start_interval.stdout }}"

- name: 1.5.2_start_timeout
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHanaTopology']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='SAPHanaTopology']/operations/op [@name='start']" | grep -oP 'timeout="\K[^"]+'||echo ""
    else
        # SAPHanaTopology is not configured
        echo "SAPHanaTopology is not configured"
    fi
  register: result_start_timeout
  changed_when: false

#- debug:
#    msg: "{{ result_start_timeout }}"

- include_role:
    name: "set-results"
  vars:
    fact_name: "1.5.2_start_timeout"
    fact_value: "{{ result_start_timeout.stdout }}"

- name: 1.5.2_stop_interval
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHanaTopology']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='SAPHanaTopology']/operations/op [@name='stop']" | grep -oP 'interval="\K[^"]+'||echo ""
    else
        # SAPHanaTopology is not configured
        echo "SAPHanaTopology is not configured"
    fi
  register: result_stop_interval
  changed_when: false

#- debug:
#    msg: "{{ result_stop_interval }}"

- include_role:
    name: "set-results"
  vars:
    fact_name: "1.5.2_stop_interval"
    fact_value: "{{ result_stop_interval.stdout }}"

- name: 1.5.2_stop_timeout
  shell: |
    if cibadmin -Q --xpath "//primitive[@type='SAPHanaTopology']/@type" > /dev/null 2>&1; then
        cibadmin -Q --xpath "//primitive[@type='SAPHanaTopology']/operations/op [@name='stop']" | grep -oP 'timeout="\K[^"]+'||echo ""
    else
        # SAPHanaTopology is not configured
        echo "SAPHanaTopology is not configured"
    fi
  register: result_stop_timeout
  changed_when: false

#- debug:
#    msg: "{{ result_stop_timeout }}"

- include_role:
    name: "set-results"
  vars:
    fact_name: "1.5.2_stop_timeout"
    fact_value: "{{ result_stop_timeout.stdout }}"
